### ISSUE TITLE
Generics support in sealed

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/MoshiX#1]
What would this look like? Is there anything we need to do? I'm not actually sure if PolymorphicJsonAdapter supports them either

```kotlin
sealed class Message<T> {
  data class Success<T>(val data: T)
  data class Failure(val reason: String)
}
```

**Comment by ZacSweers** [comment]
This isn't really possible

**Comment by extmkv** [comment]
@ZacSweers I facing exactly this issue right now.
There is no way to support this?

**Comment by ZacSweers** [comment]
There is not. PRs welcome but I could never figure out a way that made sense
