### ISSUE TITLE
Alternative API designs

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/MoshiX#10]
This is an issue to track alternative API designs for this library.

The current implementation is below. For the sake of argument, please keep alternative API proposals using the same `Message` example code.

```kotlin
@JsonClass(generateAdapter = true, generator = "sealed:type")
sealed class Message {

  @TypeLabel("success")
  @JsonClass(generateAdapter = true)
  data class Success(val value: String) : Message()

  @TypeLabel("error")
  @JsonClass(generateAdapter = true)
  data class Error(val error_logs: Map<String, Any>) : Message()

  @DefaultObject
  object Unknown : Message()
}
```

**Comment by ZacSweers** [comment]
One annotation on the message that contains all the relevant metadata. `Nothing` used as a special case for no default type. `@DefaultNull` takes precedence if `Nothing` is the default type.

```kotlin
annotation class JsonSubtypes<T : Any>(
    val typeLabel: String,
    val subtypes: Array<Subtype<out T>>,
    val defaultType: KClass<out T> = Nothing::class
) {
  annotation class Subtype<T : Any>(val type: KClass<out T>, val labelKey: String)
}

@JsonSubtypes<Message>(
    typeLabel = "type",
    subtypes = [
      Subtype(Success::class, "success"),
      Subtype(Error::class, "error")
    ],
    defaultType = Unknown::class
)
@JsonClass(generateAdapter = true, generator = "sealed")
sealed class Message {

  @JsonClass(generateAdapter = true)
  data class Success(val value: String) : Message()

  @JsonClass(generateAdapter = true)
  data class Error(val error_logs: Map<String, Any>) : Message()

  object Unknown : Message()
}
```

Pros:
- only one target containing all relevant information. Simpler for both reflection and code gen, possibly more performant due to not having to manually search.
- Makes #2 and #9 much easier

Cons:
- information about type labels or default types are detached from their types. Hard(er) to keep in sync.

**Comment by AlexKrupa** [comment]
Labels being attached to their types is my favorite thing about the current implementation. The alternative proposal seems very similar to writing an adapter manually, although we don't have to register it explicitly.

One part that feels slightly awkward to me is the `sealed:type` syntax. I'd personally prefer to have the type in a separate annotation just for consistency with subtype annotations.

```kotlin
@PolymorphicType("type")
@JsonClass(generateAdapter = true, generator = "sealed")
sealed class Message
```

**Comment by ZacSweers** [comment]
Closing this out as I think we're happy with the current implementation
