### ISSUE TITLE
Json annotation as typealias causes compilation error

### ISSUE THREAD

**Issue by efemoney** [ZacSweers/MoshiX#113]
Ran into this trying to switch from kapt(moshi.codegen) to ksp(moshix.ksp). 

In our project, we have `typealias Json = com.moshi.Json`. Allows to type `@Json("key")` instead of `@Json(name = "key")` all over our codebase plus helps if we ever need to migrate to another json (de/)serialization library.

Added a reproducer in #112.

**Comment by ZacSweers** [comment]
This is fixed on main now and will be available in the next release
