### ISSUE TITLE
Consider including moshi-adapters artifact when using moshi-sealed

### ISSUE THREAD

**Issue by ursusursus** [ZacSweers/MoshiX#114]
Hi,
when using-moshi sealed, it generates code that uses `PolymorphicJsonAdapterFactory`
I as a consumer of the library have implicitly no idea what it is unless I read the documentation, saying I need another artifact.

Why not just `api moshi-adapter` then?

**Comment by ZacSweers** [comment]
Probably just an oversight, want to send a PR?

**Comment by ZacSweers** [comment]
This is fixed on main now and will be available in the next release
