### ISSUE TITLE
Moshi-sealed-runtime: More than one file was found with OS independent path 'META-INF/runtime.kotlin_module'

### ISSUE THREAD

**Issue by slmlt** [ZacSweers/MoshiX#129]
After adding `dev.zacsweers.moshix:moshi-sealed-runtime:0.11.2` dependency, project fails to build with the following error:
`More than one file was found with OS independent path 'META-INF/runtime.kotlin_module'.`
It seems like a module name mangling problem, as stated here https://ncorti.com/blog/name-mangling-in-kotlin
Possible solution is to pass the -module-name compiler flag in the library (in fact, it might prove useful to add this statement to all moshiX libraries)

**Comment by ZacSweers** [comment]
Want to send a PR?

**Comment by slmlt** [comment]
Sure. That should fix it: https://github.com/ZacSweers/MoshiX/pull/130

**Comment by slmlt** [comment]
> Thanks! I plan to cut a release after KSP beta05 is out, hopefully this week

Thank you for the quick response! Would be great to see an update as soon as possible though, as this issue kinda blocks a feature in a project I am currently working on :)

**Comment by ZacSweers** [comment]
You're welcome to use a snapshot or build from source until then

**Comment by ZacSweers** [comment]
Resolved in 0.12.0
