### ISSUE TITLE
OptIn to ExperimentStdlibApi in generated adapters

### ISSUE THREAD

**Issue by gabrielittner** [ZacSweers/MoshiX#139]
The generated code for [object subtypes](https://github.com/ZacSweers/MoshiX/tree/main/moshi-sealed#object-subtypes) uses Moshi's experimental [addAdapter](
https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/-MoshiKotlinExtensions.kt#L31-L32) function. Since this is generated code I'd have add an OptIn for the whole project. Generally not an issue but because Moshi is using Kotlin's stdlib experimental annotation I'd also opt in to a lot of non Moshi things.

Could the generated adapter have an `@OptIn` annotation for it?

**Comment by ZacSweers** [comment]
Ah good catch, want to send a PR?

**Comment by gabrielittner** [comment]
Sure, will do so over the weekend
