### ISSUE TITLE
Improve errors and diagnostics

### ISSUE THREAD

**Issue by martinbonnin** [ZacSweers/MoshiX#152]
I had a leftover (wrong) `@JsonAdapter` annotation:

```kotlin
@JsonClass(generateAdapter = true, generator = "sealed:kind")
data class MyClass(val prop1: String, val prop2: Int)
```
The error in this case is:

```
> Task kspKotlin FAILED
e: [ksp] java.lang.IllegalStateException: Must be a sealed class!
```

It would be nice if the error included the source location where it is.

**Comment by ZacSweers** [comment]
Hmm, it should be reporting that. I'll double check
