### ISSUE TITLE
Interest check: Gson to Moshi migration helper tools

### ISSUE THREAD

**Issue by trevjonez** [ZacSweers/MoshiX#161]
I find myself on multiple occasions now writing helpers for Retrofit, Moshi, and GSON to aid in doing an incremental migration of the JSON tooling in a project. 

I wonder if you would be open to a PR adding a module for inclusion in the MoshiX group?

Usually comes down to roughly these 4 elements:

```kotlin
/**
 * Detects if [okhttp3.RequestBody] or [okhttp3.ResponseBody] type is
 * annotated with [com.squareup.moshi.JsonClass] on converter lookup.
 * If it does, delegate to [retrofit2.converter.moshi.MoshiConverterFactory]
 * otherwise use [retrofit2.converter.gson.GsonConverterFactory].
 */
class GsonToMoshiMigrationConverterFactory(
    private val gsonConverterFactory: GsonConverterFactory,
    private val moshiConverterFactory: MoshiConverterFactory,
) : Converter.Factory() { ... }
```

```kotlin
/**
 * Detect [com.squareup.moshi.JsonClass], 
 * [com.squareup.moshi.Json],
 * and [com.squareup.moshi.JsonQualifier] 
 * annotated elements during [TypeAdapter] lookup.
 *
 * Throws [UnsupportedOperationException] if mixed json tooling is found.
 */
class NestedMoshiDetectorFactory : TypeAdapterFactory { ... }
```

```kotlin
/**
 * Detect [com.google.gson.annotations.JsonAdapter] 
 * and [com.google.gson.annotations.SerializedName]
 * annotated elements during [JsonAdapter] lookup.
 * 
 * Throws [UnsupportedOperationException] if mixed json tooling is found.
 */
class NestedGsonDetectorFactory : JsonAdapter.Factory { ... }
```

```kotlin
/**
 * Usages of this are usually rare but provides a way to bypass nested checks explicitly.
 */
@Retention(RUNTIME)
annotation class AllowMixedJson
```

Friends don't let friends use GSON 😉

**Comment by ZacSweers** [comment]
Do you know about [moshi-gson-interop](https://github.com/slackhq/moshi-gson-interop)?

**Comment by trevjonez** [comment]
Oh that is funny. You would already have something in place. I was not aware

A quick skim and the only key difference I believe I am seeing is that your solution is far more flexible for mixing the two.

So just a difference in migration strategy really it seems. I want to make it blow up if you try to mix at all, so that people are forced to be more thorough sooner.

Then by doing the gson vs moshi at the retrofit level I am able to cut down how much logic I have to support for the okio into gson behavior. But the trade off being it assumes retrofit is the better place to decide which to use, likely not globally true.

**Comment by ZacSweers** [comment]
Considering how often models mix, I don't really think that's a safe method :/. As such I'm reluctant to add anything to MoshiX around it. Sorry!
