### ISSUE TITLE
Add type information to DefaultObject to improve debugging

### ISSUE THREAD

**Issue by sebaslogen** [ZacSweers/MoshiX#26]
@DefaultObject annotation works fine to define unknown types and we log them to Cashlytics as non-fatal errors to track problems parsing items in production apps.

The problem is that these default objects do not include any information about the unknown type found in the original JSON response, it would be very helpful if we could add a string value to the default object/class to debug unknown types in the wild.

**Comment by ZacSweers** [comment]
I think you should do this at the Moshi level with a delegating intermediary adapter. There's no clean API hook for this in moshi-sealed as in a code gen world it's entirely annotation-based. You would basically make a pass-through JsonAdapter.Factory that peeks the key like the polymorphic adapter does, try/catches a delegate fromJson, and logs your unknown key if it fails
