### ISSUE TITLE
Question: objects support?

### ISSUE THREAD

**Issue by plnice** [ZacSweers/MoshiX#27]
Is following class structure, with objects not carrying any additional information, somehow achievable using moshi-sealed?

```kotlin
@JsonClass(generateAdapter = true, generator = "sealed:type")
sealed class Message {

  @TypeLabel("success")
  @JsonClass(generateAdapter = true)
  data class Success(val value: String) : Message()

  @TypeLabel("error")
  @JsonClass(generateAdapter = true)
  object Error : Message()

  @TypeLabel("another_error")
  @JsonClass(generateAdapter = true)
  object AnotherError : Message()
}
```

This would allow us to differentiate between types using "when" clause:

```
when (message) {
  is Success -> ...
  Error -> ...
  AnotherError -> ...
}
```

However, this class structure causes annotation processing to fail:
```
error: @JsonClass can't be applied to com.myapp.Error: must be a Kotlin class
```

When I remove `@JsonClass` annotation, I get another error:
```
error: Unhandled object type, cannot serialize this.
```

As a workaround I (probably) can change `Error`/`AnotherError` to `class`, but this requires to suppress `CanSealedSubClassBeObject` warning raised by Kotlin compiler.

**Comment by ZacSweers** [comment]
Not possible until Moshi supports it. I've [prototyped the idea](https://github.com/square/moshi/pull/934) in the past but nothing has come of it yet. Feel free to file an issue over there with a proposal

**Comment by ahmed3elshaer** [comment]
@ZacSweers I think it would be really helpful i have faced the same issue and without https://github.com/ZacSweers/moshi-sealed which i found by total chance on checking your profile to Follow you 😅  you saved my day <3

**Comment by ZacSweers** [comment]
I'm working on an idea for this now in the `z/objects` branch. I have it working in reflection, just need to add code gen support for it too now
