### ISSUE TITLE
Plugin with id 'dev.zacsweers.moshix' not found.

### ISSUE THREAD

**Issue by vudzkostek** [ZacSweers/MoshiX#270]
For unknown reason I started getting (gradle configuration phase):
```
Could not apply requested plugin [id: 'dev.zacsweers.moshix', version: '0.17.0'] as it does not provide a plugin with id 'dev.zacsweers.moshix'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> Plugin with id 'dev.zacsweers.moshix' not found.
```
for a module that had plugin for quite some time.

Module plugin section
```gradle
plugins {
    id("com.android.library")
    id("kotlin-kapt")
    id("dev.zacsweers.moshix")
}
```
settings.gradle
```gradle
pluginManagement {
    plugins {
        id("dev.zacsweers.moshix") version "0.17.1" // downgrade to 0.17.0 doesn't help
    }
}
```

I can remove that plugin from that particular module and build project just fine (there are other modules with this module and there's no issue). But when I restore it I am getting exception again. I add this module so that it generates proper proguard rules for adapters, otherwise release builds crash. I could probably add these rules myself, nevertheless, it is weird it happens only with that module.

**Comment by ZacSweers** [comment]
Without a repro project there's no much I can do to advise here
