### ISSUE TITLE
toJson on a @DefaultObject

### ISSUE THREAD

**Issue by Frank1234** [ZacSweers/MoshiX#28]
Is it possible to do a `toJson()` on an object tree with DefaultObjects? 

Running a `toJson()` on the result of a `fromJson()` doesn't work if any of the incoming types in the tree were unknown (`@DefaultObject`).

The error: 
```
Expected one of [...] but found com.[].UnknownAction. Register this subtype. 
at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.toJson(PolymorphicJsonAdapterFactory.java:286) 
```
(UnknownAction is my `@DefaultObject`)

Is there a way around this?

**Comment by ZacSweers** [comment]
Can you elaborate or share an example?

**Comment by Frank1234** [comment]
Example below.

```

@JsonClass(generateAdapter = true, generator = "sealed:type")
sealed class MyModel {

    @TypeLabel("SEARCH")
    @JsonClass(generateAdapter = true)
    data class MyModelSearch(val term: String) : MyModel()

    @DefaultObject
    object MyModelUnknown : MyModel()
}

try {
    
    val jsonString = """{
        "type": "NOT-SEARCH",
        "term": "dummy"
      }"""

    val adapter = Moshi.Builder().build().adapter(MyModel::class.java)
    val jsonObj = adapter.fromJson(jsonString)

    System.out.println("jsonObj " + jsonObj.toString()) // correct: prints MyModelUnknown

    val newJsonString = adapter.toJson(jsonObj) // IllegalArgumentException: Expected one of...
    
} catch (e: Exception) {
    System.out.println(e)
}
```

**Comment by Frank1234** [comment]
Is the problem clear now?

**Comment by ZacSweers** [comment]
I've been busy and haven't had time to look

**Comment by ZacSweers** [comment]
It can only handle defaulting to an unknown decoded type, but that should only happen in fromJson cases. If you get an unknown type, you should not be trying to re-encode it again. This would be like a client intentionally trying to encode an unknown type, which is sort of a pathological case

**Comment by Frank1234** [comment]
okay. saving it as an object stream instead.
