### ISSUE TITLE
Java 11 in 0.21.0 explained?

### ISSUE THREAD

**Issue by ursusursus** [ZacSweers/MoshiX#382]
Hi, I'm trying to update to `0.21.0` and I'm gettings 

```
 What went wrong:
Execution failed for task ':auth:api-client:contract:kspKotlin'.
> Could not resolve all files for configuration ':auth:api-client:contract:compileClasspath'.
   > Could not resolve dev.zacsweers.moshix:moshi-sealed-runtime:0.21.0.
     Required by:
         project :auth:api-client:contract
      > No matching variant of dev.zacsweers.moshix:moshi-sealed-runtime:0.21.0 was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
          - Variant 'apiElements' capability dev.zacsweers.moshix:moshi-sealed-runtime:0.21.0 declares an API of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
          - Variant 'runtimeElements' capability dev.zacsweers.moshix:moshi-sealed-runtime:0.21.0 declares a runtime of a library, packaged as a jar, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm':
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
```

Then I'm reading release notes (https://github.com/ZacSweers/MoshiX/releases/tag/0.21.0) saying 
```
Update to JVM target 11 by @ZacSweers in https://github.com/ZacSweers/MoshiX/pull/359
```

And I'm confused. Java 11 is meant for my machine, i.e. the plugin, not the runtime right? (which is set to 1.8)
If so, then I'm still confused as I obviously have a JDK 11 on my machine, which Android Studio requires.

Also, if it is any help, this error only comes up in pure kotlin modules, like this 

```
apply plugin: "kotlin"
apply plugin: "com.google.devtools.ksp"

dependencies {

    implementation deps.moshi.client
    implementation deps.moshi.adapters
    implementation deps.moshi.sealed
    ksp deps.moshi.compiler
    ksp deps.moshi.sealedCompiler

    api project(":scoped")
}
```

but not in android modules (where ksp && moshi compiler is applied)

**Comment by ZacSweers** [comment]
It is for the runtime and the plugin. Java 8 reached EoL a year ago and I am no longer supporting it in my projects.

**Comment by ursusursus** [comment]
wait, doesn't that effectively then make this library minSdk 33?

**Comment by ZacSweers** [comment]
No, it assume android projects use D8. We've targeted Java 11 at slack for nearly two years. https://jakewharton.com/androids-java-9-10-11-and-12-support/

**Comment by ursusursus** [comment]
But what minSdk does then bumping to jvm to 11 then implies? Does it even? Since D8 would desugar to whatever's possible on a given platform? 

Also, why does this even matter, for a kotlin library? (when language features are irrelevant, and apis are a different story)
Is it purely because higher java version `javac` will produce bytecode leveraging new instructions and therefore better performance (on the platform versions where the java version is natively)?

If so, then was I leaving performance on the table for no reason for 2 years?
Also, why java 11 then, why not whatever is the latest in latest android version?

(Would you happen to have a map of android api level to java language version, please? Can't seem to find it)

**Comment by ZacSweers** [comment]
The question is never "why should I update", but rather "why shouldn't I". D8 (language features) and L8 (backported APIs) make java 11 entirely accessible for modern android development and there's no reason not to use the most modern language version that you can.

I'm not really interested in debating or explaining everything else you went on about as it's tangential to this library at best.

**Comment by ursusursus** [comment]
I'm not arguing against it, I'm just genuinely trying to understand the reasoning for it in a kotlin library. I've done some research as not to be annoying, and came up with these - to update to jvm 11 would mean for a kotlin library:

1. when the consuming application is non-android, it is to benefit from java 11 bytecode, making it more efficient/performant
2. when the consuming application is android, then any new bytecode is desugared, and therefore no efficiency/performance benefits, however one can update because D8 fully supports Java 11 bytecode, and should update as to move the industry forward and let EOL software die

Would these two points be correnct, please?
