### ISSUE TITLE
Missing adapters in AGP 7.4 with Moshi-ir codegen.

### ISSUE THREAD

**Issue by hrach** [ZacSweers/MoshiX#396]
Hi, we have a problem with R8 minification and JsonAdapters missing in the build (generated by moshi ir). Do you have any idea where the issue can be? I've tried searching issuetracker.google.com and here, but haven't found anything useful.

Started being broken after the update to AGP 7.3.2->7.4.2:

Libs used:
- Gradle 8.0.2
- AGP 7.4.2
- R8 4.0.52 (implicit)
- MoshiX 0.21.0
- Moshi 1.14.0

Error:
```
 Caused by: java.lang.ClassNotFoundException: com.xxxx.BatchRequestJsonAdapter
```

This fixes it for us:

```
-keep class com.xxx.**.*JsonAdapter { *; }
```

**Comment by ZacSweers** [comment]
Can you put together a minimally reproducing sample? I can't help much without one

**Comment by apramana** [comment]
Interesting, I saw adapters disappear after updating Gradle 7.6 -> 8.0.0

**Comment by hrach** [comment]
We did Gradle 8 update as well. So maybe I've just wrongly debugged the issue. How did you solve the mising adapters with Gradle 8?

**Comment by hrach** [comment]
Haven't you chance to take a look at the reproduction? Thank you.

**Comment by ZacSweers** [comment]
Your repro doesn't have any instructions on how to build it and contains no gradle wrapper files. I added some and see the same behavior. I think you answered it for yourself - the realm plugin is somehow removing or losing the generated adapter class. You should file a bug with them, this isn't a moshi-ir issue

**Comment by rorbech** [comment]
@ZacSweers The proguard configuration created from the MoshiX-plugin is not registered as input for the `mergeReleaseGeneratedProguardFiles` task when applying the version of the realm-plugin that uses the new transformer API (see https://github.com/ZacSweers/MoshiX/issues/396#issuecomment-1457361902 for details). Could it be that the task is not registered properly for the new transformer pipeline, or do you know the convention around how to propagate stuff like additional proguard rules through that?

**Comment by ZacSweers** [comment]
I am not familiar with realm or the transformer API it's using

**Comment by rorbech** [comment]
The transformer API is part of Android Gradle Plugin, so not Realm specific. The task infrastructure was reworked quite heavily from AGP 7.2 -> 7.4, so I just suspect that the conventions for locating `ProcessResources`-task in https://github.com/ZacSweers/MoshiX/blob/main/moshi-ir/moshi-gradle-plugin/src/main/kotlin/dev/zacsweers/moshix/ir/gradle/MoshiGradleSubplugin.kt#L76 is not compatible with the possible variances in the task graph with AGP 7.4+.

**Comment by ZacSweers** [comment]
We are using it with AGP 7.4 and 8.0 without issues. This also only appears to occur when the realm plugin is applied and not with any other plugins (we have some bytecode processing plugins at my work). I'm not against fixing a bug if there is one here, but currently I'm not seeing it or an obvious better thing to do :/

**Comment by rorbech** [comment]
Might be that we are not forwarding the inputs/outputs correctly in the new pipeline, but I just couldn't see any paths, API or conventions around handling things other than the ones intended to go into the final jar. Will have to debug and see the various pieces in action to get an idea of what is missing in wiring it up.
