### ISSUE TITLE
MoshiX generates malformed proguard rule

### ISSUE THREAD

**Issue by sav007** [ZacSweers/MoshiX#415]
Latest version of MoshiX sealed leads to malformed proguard rules.
The cause of issue was the `data` package name like: `com.example.data`

The generated proguard rule:
```
# Conditionally keep this adapter for every possible nested subtype that uses it.
-if class com.example.`data`.Model
-keep class com.example.data.ModelJsonAdapter {
    public <init>(com.squareup.moshi.Moshi);
}
```
Error:
```
AGPBI: {"kind":"error","text":"Expecting '-keep' option after '-if' option.","sources":[{"file":".../build/intermediates/consumer_proguard_dir/release/lib0/proguard.txt","position":{"startLine":57,"startColumn":0,"startOffset":2994,"endColumn":41,"endOffset":3035}}],"tool":"R8"}
```

Not 100% sure what the cause of this but it looks like KotlinPoet changed the returned value in `reflectionName()`:

https://github.com/ZacSweers/MoshiX/blob/612e921c70b0a9292873a92e3513d39c56afbd67/moshi-sealed/codegen/src/main/kotlin/dev/zacsweers/moshix/sealed/codegen/ProguardConfig.kt#L57

**Comment by ZacSweers** [comment]
Which version of Kotlinpoet are you using?

**Comment by sav007** [comment]
Yeah, I guess you are right will reference this one in that issue.

**Comment by sav007** [comment]
I wasn't able to reproduce this issue with plain KPoet, but have one guess:

1. If you create a class like `ClassName("com.sample.data", "Model").reflectionName()` it returns the name without escaping: `com.sample.data.Model`
2. But if you call on that class toString `ClassName("com.sample.data", "Model").toString()` it returns an escaped string `com.sample.'data'.Model`
3. Next if you create class name with a escaped string like `ClassName("", "com.sample.`data`.Model").reflectionName()` then it returns escaped `com.sample.'data'.Model`

That makes me think if there any possible transformation in the codegen that leads to passing `targetClass:ClassName` with escaped package name to `ProguardConfig`. It mightbe a case where ClassName has been created with escaped package name  somewhere ?

I also tried to reproduce with the `MoshiSealedSymbolProcessorProviderTest` but wasn't able, though I see a little different result. If I change test fixture to have `package test.data` the generated adapter content will have:
```
// Code generated by moshi-sealed. Do not edit.
package test.`data`
....
```
even this valid source code, but I guess it should be non escaped package name.

I still will try to repro issue we see in our project with escaped proguard rule, but does above ^^^ gives any ideas where the issue is?

**Comment by ZacSweers** [comment]
I did not understand your third bullet, maybe because the formatting broke. Why would you make a class like `ClassName("", "com.sample.data.Model")`? That seems like a programmer error

**Comment by ZacSweers** [comment]
Closing as wontfix as there's been no followup
