### ISSUE TITLE
Kotlinx Immutable Collection JSON Adapters

### ISSUE THREAD

**Issue by brentwatson** [ZacSweers/MoshiX#460]
I have created JsonAdapter classes to deserialize `PersistentList` and `PersistentMap` types from [kotlinx.collections.immutable](https://github.com/Kotlin/kotlinx.collections.immutable) and I'm looking for the right place to share these with the community. @ZacSweers do you think these make sense to contribute to MoshiX under `moshi-adapters`?

**Comment by ZacSweers** [comment]
I'd be open to adding them here, but as a separate artifact given the dependency. `moshi-adapters-kotlinx-immutables`?
