### ISSUE TITLE
Fallback adapter type's primary constructor can only have a Moshi parameter

### ISSUE THREAD

**Issue by overfullstack** [ZacSweers/MoshiX#549]
A [Test](https://github.com/overfullstack/my-lab/blob/a38446857083b67f4bcf59fea4e54be330fa8402/moshi/src/test/kotlin/ga/overfullstack/adapter/MessageTest.kt#L44) to replicate this

I am not able to run this test as I get this error. 

```
e: file:///Users/gopala.akshintala/code-clones/my-github/my-lab/moshi/src/test/kotlin/ga/overfullstack/adapter/MessageTest.kt:32:3 Fallback adapter type's primary constructor can only have a Moshi parameter
```

I took this example from [moshix-sealed sample](https://github.com/ZacSweers/MoshiX/blob/5e228619b3f0cdfd2b6db990174825de7b8ba563/moshi-sealed/sample/src/test/kotlin/dev/zacsweers/moshix/sealed/sample/test/MessageTest.kt#L101). But I get the same error when I paste this test in [moshi-kotlin-tests](https://github.com/ZacSweers/MoshiX/tree/main/moshi-ir/moshi-kotlin-tests/src/test/kotlin/dev/zacsweers/moshi/sealed) and execute it

**Comment by ZacSweers** [comment]
Can you paste the stacktrace of the error you're referring to?

**Comment by overfullstack** [comment]
@ZacSweers this is the only stacktrace I find, even with running the test with `--stacktrace`.  Is there anyway I can debug the plugin code?

```
e: file:///Users/gopala.akshintala/code-clones/my-github/my-lab/moshi/src/test/kotlin/ga/overfullstack/adapter/MessageTest.kt:32:3 Fallback adapter type's primary constructor can only have a Moshi parameter
```

To overrule the possibility of any setup issue on my repository, I copy pasted the same test into MoshiX repository, right in this package: [moshi-kotlin-tests](https://github.com/ZacSweers/MoshiX/tree/main/moshi-ir/moshi-kotlin-tests/src/test/kotlin/dev/zacsweers/moshi/sealed?rgh-link-date=2024-02-03T11%3A29%3A42Z) and you should be able to reproduce the issue.
