### ISSUE TITLE
Int-based labels

### ISSUE THREAD

**Issue by hpinhal** [ZacSweers/MoshiX#65]
Is it possible to use a non-string label? Currently working with a JSON like the following:

```
{
    "state": 0,
    "message": "..."
}

{
    "state": 1,
    "token": "..."
}
```

I've set up the sealed class with a `DefaultObject` and with the example I have, it always falls back to the default object instead of the concrete type. I've tested with a string value (`"1"`) and it resolves to the correct type. However, the json structure is not something I can change.

```kotlin
@JsonClass(generateAdapter = true, generator = "sealed:state")
sealed class State {

    @TypeLabel("0")
    @JsonClass(generateAdapter = true)
    data class Loading(
        val message: String
    ) : State()

    @TypeLabel("1")
    @JsonClass(generateAdapter = true)
    data class Power(
        val token: String,
    ) : State()

    @DefaultObject
    object Unknown : State()
}
```

Is there an alternative to have an Int-based label?

**Comment by ZacSweers** [comment]
I don't want to add support for custom key types, but also not sure how to work around it right now. One (ugly) thing you could do is write a delegating adapter that uses the jsonValue APIs to make an intermediary map, then replace the type key in the map with a string value of it instead. Hand-wavy mobile typing and not ideal, but I think it would at least _work_

**Comment by hpinhal** [comment]
That's pretty much the approach taken. 
Would be nice to have a more flexible API but after taken a look at the source I can understand your standpoint.
