### ISSUE TITLE
Support @TypeLabel on @DefaultObject to make it serializable

### ISSUE THREAD

**Issue by dmo60** [ZacSweers/MoshiX#76]
Hey! Thanks for `moshi-sealed`, we are using it heavily in our project.

With the support for `object` subtypes, I was wondering if it would be possible (and desireable) to support a type label on the default object. So basically making the default object a supported serializable and deserializable subtype.

I can see two use cases:

1. It would allow serialization of the default object (see also #28). That's what I would be interested in. We often have a setup where we directly write a JSON API response to some cache file. If that response contains unknown subtypes that were mapped to the default object, this would fail since default objects are not serializable. The only workaround is to filter out the default object instances before writing. One downside though is that this can get more complex if there are sealed types in different levels of the object hierarchy. Another one is that we usually only want to do further processing and handling of unknown subtypes further down in the processing chain.
Example:
```
@JsonClass(generateAdapter = true, generator = "sealed:type")
sealed class ListItem

@TypeLabel("typeA")
@JsonClass(generateAdapter = true)
data class ListItemA(...) : ListItem()

@TypeLabel("unknown")
@DefaultObject
object UnknownListItem : ListItem()

// --------
adapter.toJson(listOf(ListItemA, UnknownListItem))  // result: [{ "type": "typeA" }, { "type": "unknown" }]"
```
2. It would allow to define one of the "supported" subtypes as a fallback for "unsupported" types. Not sure if there are many use-cases, but I could imagine something like a registered "Error" subtype where additionally all unregistered types would map to:
```
@JsonClass(generateAdapter = true, generator = "sealed:type")
sealed class OperationResult

@TypeLabel("success")
@JsonClass(generateAdapter = true)
data class Success(...) : OperationResult()

@TypeLabel("error")
@DefaultObject
object Error : OperationResult()

//----------------
adapter.fromJson(""" { "type": "error" } """)  // result: Error
adapter.fromJson(""" { "type": "some_unknown_result" } """)  // result: Error
```

The downside I see is that it would break symmetry of `fromJSON`/`toJSON`, but I guess it would be obvious enough from the semantics that nobody should be surprised about it.

---
My naive understanding is that something like this would be possible by generating an adapter that has the default value additionally registered as a valid subtype (refering to Example 1):
```
PolymorphicJsonAdapterFactory
        (...)
        .withSubtype(UnknownListItem::class.java, "unknown")
        .withDefaultValue(UnknownListItem)
```
Currently, adding a `@TypeLabel` to a `@DefaultObject` compiles fine, but the default object is not registered as a subtype.

**Comment by ZacSweers** [comment]
I don't think either of those two use cases are compelling enough to break the symmetry here. Particularly the first one, caching responses seems very much like something that should be done at a layer _before_ decoding, not after. Unknown objects are solely intended to indicate "I don't know what this is", which is an inherently unintentional state. I think it's worth added a check for both annotations being present though, that should be an error.
