### ISSUE TITLE
Allow `JsonString` to be used in Retrofit

### ISSUE THREAD

**Issue by efemoney** [ZacSweers/MoshiX#82]
This is for those cases where you want the json string of a response. 

The 'usual' way would be to define your service method return type as `ResponseBody` and call `ResponseBody.string()` at the call site to get the json string but this slight indirection is not necessary
```kotlin
interface Service {

  @GET("the/good/stuff") suspend fun goodStuff(): ResposeBody
}
// myService.goodStuff().string()
```

Being able to just annotate the method with `@JsonString` with a return type of `String` is much better. 

Right now the `@JsonString` annotation targets are `PROPERTY, FIELD`. Adding `FUNCTION` to that should fix this with no other changes.

**Comment by ZacSweers** [comment]
That seems reasonable to me. That would also allow this to work in auto value models. Want to send a PR?

**Comment by efemoney** [comment]
Yeah I'll do that. Gimme a couple mins.
