### ISSUE TITLE
Java support

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/MoshiX#9]
Right now this is oriented toward Kotlin sealed classes, but we could pretty easily extend it to support Java via #2. Would require a basic Java reflection artifact that does almost all of what the current reflect artifact does, then just make the kotlin-reflect artifact use this but provide a custom mapping of the sealed subtypes rather than the reflective implementation of reading annotations.

**Comment by ZacSweers** [comment]
Note this wouldn't support default objects, only default null. We could _maybe_ finagle something like a single-member enum, but can cross that bridge later.

**Comment by chrisjenx** [comment]
What is this Java you speak of... :trollface:

**Comment by ZacSweers** [comment]
Folding into #2, if ever
